# Generated by Django 5.1.4 on 2024-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapp',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_logos/'),
        ),
    ]
