# Generated by Django 5.1.4 on 2024-12-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_app_userprofile_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.androidapp'),
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
